speaker_encoder:
  speaker_encoder_hidden: 256

transformer:
  encoder_layer: 4
  encoder_head: 2
  encoder_hidden: 192
  feed_forward_expansion_factor: 4
  conv_expansion_factor: 2
  input_dropout_p: 0.1
  feed_forward_dropout_p: 0.1
  attention_dropout_p: 0.1
  conv_dropout_p: 0.1
  conv_kernel_size: 31
  half_step_residual: True

posterior_encoder:
  posterior_encoder_kernel_size: 5 
  posterior_encoder_dilation_rate: 1 
  posterior_encoder_n_layers: 16 
  
residual_coupling_block:
  residual_coupling_block_kernel_size: 5
  residual_coupling_block_dilation_rate: 1
  residual_coupling_block_n_layers: 4
  residual_coupling_block_n_flows: 4

variance_predictor:
  filter_size: 256
  kernel_size: 3
  dropout: 0.5
  cwt_hidden_size: 128
  cwt_std_scale: 0.8
  cwt_out_dims: 11
  cwt_stats_out_dims: 2

variance_embedding:
  energy_quantization: "linear" # support 'linear' or 'log', 'log' is allowed only if the energy values are not normalized during preprocessing
  n_bins: 256
  
generator:
  resblock: "1"
  segment_size: 8192
  generator_hidden: 192
  upsample_rates: [8,8,2,2]
  upsample_kernel_sizes: [16,16,4,4]
  upsample_initial_channel: 512
  resblock_kernel_sizes: [3,7,11]
  resblock_dilation_sizes: [[1,3,5], [1,3,5], [1,3,5]]

temperature: 0.0005

max_seq_len: 1000
